name: Test

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    name: eslint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]

    steps:
      - uses: actions/checkout@v1
      - name: run test
        run: |
          node --version
          yarn install
          yarn lint
